services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  wordpress:
    image: wordpress:5-php8.0-apache
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/wp-content/plugins/handball
    environment:
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_HOST: mariadb
