services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./sql/001_init.sql:/docker-entrypoint-initdb.d/init.sql

  wordpress:
    image: wordpress:6-php8.2-apache
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/wp-content/plugins/handball
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DEBUG: 1
